apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-nfs
  namespace: default
  # labels:
  #   app: myapp
  #   tier: fronttend
  # annotations:
  #   magedu.com/created-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    # ports:
    #   - name: http
    #     containerPort: 80
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html/
  volumes:
    - name: html
      nfs:
        path: /data/volumes
        server: 192.168.56.133

    
    