apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: default
  labels:
    app: myapp
    tier: fronttend
  annotations:
    magedu.com/created-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports:
      - name: http
        containerPort: 80
    volumeMounts:
      - name: html
        mountPath: /data/web/html
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command:
      - "/bin/sh"
      - "-c"
      - "sleep 3600"
    volumeMounts:
      - name: html
        mountPath: /data/
  volumes:
    - name: html
      emptyDir: {}
    
    